server:
  port: 8081

spring:
  application:
    name: customer-test
  profiles:
    - test
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/customerTest
    password: gremio83

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

jwt:
  security:
    key: segredo
    expiration: 846000000