spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/wesleyschwartz/Projeto-ShopStyle-Compass/tree/main/config_server/properties_microservices


server:
  port: 8888
